import './globals.css'
import type { Metadata } from 'next'
import { ClientSideSessionProvider } from "./auth/components";
import { Inter } from 'next/font/google'
import { PageContainer } from './components/PageContainer';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientSideSessionProvider>
          <PageContainer>
            {children}
          </PageContainer>
        </ClientSideSessionProvider>
      </body>
    </html>
  )
}
